---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-microservices-deployment
  labels:
    app: auth-microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-microservices
  template:
    metadata:
      labels:
        app: auth-microservices
    spec:
      containers:
        - name: auth-microservices
          image: mint/auth-microservice:1.0.2
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: kafka-url
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-microservices-deployment
  labels:
    app: payments-microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payments-microservices
  template:
    metadata:
      labels:
        app: payments-microservices
    spec:
      containers:
        - name: payments-microservices
          image: mint/payments-microservice:1.0.2
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: kafka-url
